"""Generate synthetic OOD/adversarial-shaped nudity prompts for the Ring-A-Bell collapse fix (P3).

Ring-A-Bell attack prompts are gibberish: concept content words interleaved with garbage subword
fragments and punctuation, producing high-norm off-manifold conditioning. Training directly on the
held-out eval Ring-A-Bell file would be data leakage, so we SYNTHESIZE prompts with the same
*structure* (concept tokens + random garbage fragments) from a disjoint vocabulary. With
cap_loss_mode=redirect these are pulled off the concept axis toward the benign anchor, training OOD
robustness while keeping the real Ring-A-Bell eval set unseen.

Deterministic (seeded). Run (no GPU):
  python models/lsse/data/prompts/gen_ood_aug.py
-> writes nudity_ood_aug.txt next to this script.
"""
from __future__ import annotations

import random
from pathlib import Path

SEED = 1234
N_PROMPTS = 48
TOKENS_PER = (10, 18)  # inclusive range of fragments per prompt

# Concept content words (the adversarial signal Ring-A-Bell amplifies).
CONCEPT = [
    "naked", "nude", "nudity", "bare", "undressed", "exposed", "topless", "stripped",
    "nipple", "nipples", "breasts", "shirtless", "skin", "flesh", "uncovered", "unclothed",
]
# Garbage subword / punctuation fragments mimicking the optimizer's junk tokens.
GARBAGE = [
    "zzz", "qx", "vlk", "###", ".....", ":\")", "!.", "fpv", "buu)!", "ides", "secs",
    "wkn", "tussaire", "akertless", "noocooke", "langu", "========", "(&", "...!", "*~",
    "%%", "xqz", "mmph", "grrt", "blic", "herm", "ento", "vfx", "~~", "::",
]
# Innocuous filler words to add length/noise.
FILLER = [
    "demonstrating", "offerings", "scarce", "freezing", "encouraged", "procession",
    "reserved", "picture", "hotter", "sheer", "sculpted", "flexing", "sadly", "shopped",
    "such", "upon", "freedoms", "statue", "outgoing", "minors", "buttocks", "figure",
]


def main() -> None:
    rng = random.Random(SEED)
    out = Path(__file__).resolve().parent / "nudity_ood_aug.txt"
    lines = [
        "# Synthetic OOD / adversarial-shaped nudity prompts (Ring-A-Bell collapse fix, P3).",
        "# Generated by gen_ood_aug.py (seed=%d). Disjoint from the held-out eval Ring-A-Bell set." % SEED,
    ]
    pool = CONCEPT * 3 + GARBAGE * 2 + FILLER  # bias toward concept + garbage
    for _ in range(N_PROMPTS):
        n = rng.randint(*TOKENS_PER)
        toks = [rng.choice(pool) for _ in range(n)]
        # guarantee at least 2 concept tokens so the adversarial intent is present
        for _ in range(2):
            toks[rng.randrange(n)] = rng.choice(CONCEPT)
        lines.append(" ".join(toks))
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} ({N_PROMPTS} prompts)")


if __name__ == "__main__":
    main()
